// nuxt/pages/index.vue
<template>
  <el-row class="flex flex-col items-center justify-center">
    <el-row>
      <span>Iconify</span>
      <v-icon icon="logos:vue"></v-icon>
    </el-row>
    <el-row>
      <span>Nuxt Icon</span>
      <Icon name="logos:vue"></Icon>
    </el-row>
    <el-row>index</el-row>
    <el-row class="mt-4">
      <el-button @click="$router.push('/sign-in')">SIGN IN</el-button>
    </el-row>
  </el-row>
</template>

// react/src/pages/Index.tsx
import { Row, Button } from 'antd';
import { DefaultLayout } from '@/layouts';

const Index = memo(() => {
  const navigate = useNavigate();

  return (
    <DefaultLayout>
      <Row className="flex flex-col items-center justify-center">
        <Row>index</Row>
        <Row className="mt-4">
          <Button onClick={() => navigate('SignIn')}>SIGN IN</Button>
        </Row>
      </Row>
    </DefaultLayout>
  );
});

export default Index;
