// nuxt/layouts/default.vue
<script setup lang="ts">
import { LayoutNetwork, LayoutVersion } from './components';
</script>

<template>
  <!-- 滚动条美化需要在布局设置背景色 -->
  <el-container class="relative h-screen bg-white">
    <el-main class="p-20">
      <NuxtPage />
    </el-main>
    <el-footer class="flex items-center justify-center">
      <layout-network />
      <layout-version />
    </el-footer>
  </el-container>
</template>

// react/src/layouts/default.tsx
import { Layout } from 'antd';
import { LayoutNetwork, LayoutVersion } from './components';

const { Footer, Content } = Layout;

export const DefaultLayout = memo(({ children }: { children?: React.ReactNode }) => {
  // const [token] = useToken();
  // const navigate = useNavigate();
  // const location = useLocation();
  // console.log('location', location);

  // useEffect(() => {
  //   if (!token && location.pathname !== '/SignIn') {
  //     navigate('/SignIn');
  //   }
  // }, [token, navigate, location]);

  return (
    <Layout className="relative h-screen">
      <Content className="p-20">{children}</Content>
      <Footer className="flex items-center justify-center">
        <LayoutNetwork />
        <LayoutVersion />
      </Footer>
    </Layout>
  );
});

export default DefaultLayout;
