// vue/src/layouts/components/version.vue
<script setup lang="ts">
import pkg from '@/../package.json';

defineOptions({
  name: 'LayoutVersion',
});
</script>

<template>
  <div class="h-8 flex items-center justify-center">
    <i-carbon-version class="mx-2"></i-carbon-version>
    <span class="mr-2">v{{ pkg.version }}</span>
  </div>
</template>

// react/src/layouts/components/Version.tsx
import { Icon } from '@iconify/react';
import pkg from '@/../package.json';

export const LayoutVersion = memo(() => (
  <div className="flex h-8 items-center justify-center">
    <Icon icon="carbon:version" className="anticon mx-2" />
    <span className="mr-2">v{pkg.version}</span>
  </div>
));

export default LayoutVersion;
